const IMG_API_URL = "https://picsum.photos/";
const IS_API_RESPONSE_SUCCESSFUL = true;
const API_RESPONSE_DELAY = 1000;
const SNACKBAR_AUTO_HIDE_DURATION = 2000;

export {
  API_RESPONSE_DELAY,
  IMG_API_URL,
  IS_API_RESPONSE_SUCCESSFUL,
  SNACKBAR_AUTO_HIDE_DURATION,
};
